shell = "/bin/zsh"

[scrolling]
history = 20000

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[bell]
animation = "Linear"
# In milliseconds. 0 to disable
duration = 10

[cursor]
style.shape = "Block"

[mouse]
hide_when_typing = true
