# If you come from bash you might have to change your $PATH.

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

#--------------#
# Original zsh #
#--------------#
#
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=1000
setopt appendhistory beep extendedglob nomatch notify
unsetopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/gleva/.zshrc'

# Initialize completion
autoload -Uz compinit
compinit

# End of lines added by compinstall

#----------------------#
# Function definitions #
#----------------------#

function sobin_fn()
{
    if [[ -f ./env/bin/activate ]]; then
        source ./env/bin/activate
    elif [[ -f ./bin/activate ]]; then
        source ./bin/activate
    else
        echo "No virtual environment found"
    fi
}

# Set prompt based on current system
function set_prompt()
{
    if [[ "$(hostname)" == "" ]]; then
        export PS1='\u:[\W]$ '
    else
        export PS1='\u@\h[\W]$ '
    fi
}

function detach_tm_clients()
{
    clients=$(tmux list-clients | sed 's/:.*//')
    for c in "$clients"; do
        tmux detach-client -t "$c"
    done
}

function back_up()
{
    if [[ "$1" == *.bak ]]; then
        restored=${1%.*}
        echo "$restored"
        mv "$1" "$restored"
    else
        cp "$1" "$1".bak
    fi
}


#----------#
# Aliases: #
#----------#

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias lf='ls -FG'
alias ls='ls --color=auto'
alias ll='ls -lG'
alias la='ls -laG'
alias mv='mv -i'
alias gs='git status'
alias gsl='git stash list'
#alias grep='grep --color=auto' # Enable grep colored output (Linux)
alias tmux='tmux -f ~/.tmux/tmux.conf'
alias tm='~/.tmux/startup.sh'
alias tmdc=detach_tm_clients
alias vim='nvim'
alias bak=back_up

# Python
alias pygrade='pip3 freeze --local | grep -v '\^e' | cut -d = -f 1 | pip3 install -U'
alias sobin=sobin_fn
alias deac="deactivate"

# Golang
alias gopath='export GOPATH=$(pwd)'

alias lsa='source ~/Scripts/load_stage_admin_profile.sh'
alias lsr='source ~/Scripts/load_stage_regular_profile.sh'
alias lpa='source ~/Scripts/load_prod_admin_profile.sh'
alias lpr='source ~/Scripts/load_prod_regular_profile.sh'
alias yat='~/Scripts/yield_at.sh'

PYTHON3_VER=$(python3 -V | awk '{ print  tolower($1 $2) }' | sed 's/\.[0-9]$//')

# Rust
alias hx='flatpak run com.helix_editor.Helix'
# TODO: remove this? Old and was for YCM. Current path seems to be ~/.cargo/bin/rustc
export RUST_SRC_PATH='/usr/local/rust/rustc-1.27.0/src'
# Enable ctrl-p ctrl-n for history
export ERL_AFLAGS="-kernel shell_history enabled"

# export PATH=$PATH:/Applications/Xcode.app/Contents/Developer/usr/bin
export PATH=~/.cargo/bin:~/.asdf/bin:~/.asdf/shims:~/.local/bin:~/bin:$PATH

export SHELL=/usr/bin/zsh
export EDITOR=nvim

if [[ -e ~/Scripts/load_nv_vars.sh ]]; then
    source ~/Scripts/load_nv_vars.sh
fi

#----------------------#
# Paths and Variables: #
#----------------------#

# fixing manpath issue
export MANPATH=/usr/man:/usr/X11/man:/usr/local/man:/usr/local/share/man:/opt/local/man:/usr/X11R6/man:/usr/share/man:
# set_prompt

# . $HOME/.asdf/asdf.sh
# . $HOME/.asdf/completions/asdf.bash
