---
  - name: "Install dotfiles"
    hosts: localhost
    connection: local
    tasks:

    - name: "Execute ls -la command"
      shell: "ls -la"
      register: "output"

    - debug: var=output.stdout_lines

    - name: "Install vim"
      ansible.builtin.package:
        name:
          - vim
        state: latest

    - name: "Install git"
      ansible.builtin.package:
        name:
          - git
        state: latest

    - name: "Install tmux"
      ansible.builtin.package:
        name:
          - tmux
        state: latest

    # - name: "Copy vim config files into place"
    #   ansible.builtin.copy:

    # - name: "Copy tmux config files into place"
    # - name: "Install vim plugins"
