---
  - name: "Install dotfiles"
    hosts: localhost
    connection: local
    tasks:

    - name: "Install vim"
      ansible.builtin.package:
        name:
          - vim
        state: latest

    - name: "Install git"
      ansible.builtin.package:
        name:
          - git
        state: latest

    - name: "Install tmux"
      ansible.builtin.package:
        name:
          - tmux
        state: latest

    - name: "Copy vim config files into place"
      ansible.builtin.copy:
        src: .vim/vimrc
        dest: ~/.vim/vimrc
        mode: '0644'

    - name: "Copy tmux config files into place"
      ansible.builtin.copy:
        src: .tmux/tmux.conf
        dest: ~/.tmux/tmux.conf
        mode: '0644'

    - name: "Copy global gitignore file"
      ansible.builtin.copy:
        src: .gitignore_global
        dest: ~/.gitignore_global
        mode: '0644'

    - name: "Install vim plugins"
      ansible.builtin.shell: 'vim +PlugInstall +qall && vim +PlugUpdate +qall'
