" A vim resource file to change settings

set modelines=0		" CVE-2007-2438

set rtp+="/usr/local/lib/python3.5/site-packages/powerline/bindings/vim"
"set rtp+="/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/powerline/bindings/vim"

" For Vundle plugin manager:
set nocompatible   " Required for Vundle
filetype off       " Required for Vundle -- why?

" Set runtime path to include Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"---------------------------------------"
" PLUGINS - keep between vundle#begin/end
"---------------------------------------"

" Let Vundle manage Vundle; required
Plugin 'VundleVim/Vundle.vim'    " V-v-v-vundle
Plugin 'scrooloose/nerdtree'     " Directory structure from vim
Plugin 'chriskempson/base16-vim' " Color schemes 
Plugin 'altercation/vim-colors-solarized'  " Solarized color scheme
"Plugin 'godlygeek/tabular'    " Dependency for vim-markdown. Keep above!
"Plugin 'plasticboy/vim-markdown'

" Autocompletion in vim by providing bindings
" to the autocompletion library 'Jedi' for Python.
"Plugin 'davidhalter/jedi-vim' 

"--------------------"
" Vundle interaction "
"--------------------"
"PluginInstall
"PluginUpdate

call vundle#end()

" Note: If installing through brew, $ brew install vim --with-python3
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

" Set for Powerline-status
set laststatus=2
" Alwyas display tabline, even if only one tab
"set showtabline=2
" Hide default insert comment below status bar
set noshowmode
" Set width of non-ascii characters
set ambiwidth=single

"--------------"
" VIM SETTINGS "
"--------------"

"""""""""""""""""""""
""" Syntax and setup
"""""""""""""""""""""
" This may cause automatic indenting
" If this doesn't format indentions correctly, try setting 'cindent' and
" 'autoindent'.
filetype plugin indent on  " Required for Vundle

" Fix backspace not working unless text is entered right before
set backspace=indent,eol,start

" set tabs to 4 spaces
set ts=4

" enter spaces when tab is pressed
set expandtab

" Hide buffers instead of closing them when you close the file.
set hidden

" Re-read an open file that has changed outside of vim
set autoread

" Use a menu for command-line completion
set wildmenu

" Use the filename for window title
set title

" Don't wrap lines
" set nowrap

" Show line numbers by default
set nu

" Show what column the cursor is currently on
set ruler

" Highlight matches when searching
set hlsearch

" C-style indentation, according to the C indentation standard.
"set cindent

" Set spellcheck on
" Change with `:set spell` or `:set nospell`
"set spell spelllang=en_us

" Set pastetoggle with <F3> key. No smart indenting, just pastes as normal.
set pastetoggle=<F3>


""""""""""""""""""""
""" Search behavior
""""""""""""""""""""
" ignore case when searching (/ or ?)
set incsearch

" automatically show matching brackets
set showmatch

" use case-sensitivity when you search w/ upper-case chars
set smartcase

" Ignore case when searchign for text
set ignorecase

""""""""""""""""""""

" 256 colors
set t_Co=256

" create mapping for quick switch between invisibles and visibles. Enable with `\l`
nmap <leader>l :set list!<CR>

" changes tab and return chars, when visible, to triangle and return symbol, respectively
"set listchars=tab:▸\ ,eol:¬

""""""""""""""""""
""" Color Schemes
""""""""""""""""""

" Start syntax highlighting, but overrule your colors with defaults.
"syntax on

" syntax enable -- keep your current color settings and turn on syntax
" highlighting. 
" This enables solarized colorscheme
syntax enable

set background=dark
"set background=light

colorscheme solarized
"colorscheme base16-3024
"colorscheme base16-brewer
"colorscheme base16-bright
"colorscheme base16-colors
"colorscheme base16-default
"colorscheme base16-google " -- Don't like this one. Yellow sucks
"colorscheme base16-harmonic16 " -- Don't like this one either now.
"colorscheme base16-pop "-- too much purple/yellow

"---------"
" ALIASES "
"---------"

" MAPPINGS
:nmap <F2> :NERDTree
