" A vim resource file to change settings

set modelines=0		" CVE-2007-2438

set rtp+="/usr/local/lib/python3.5/site-packages/powerline/bindings/vim"

" For Vundle plugin manager:
set nocompatible   " Required for Vundle
filetype off       " Required for Vundle -- why?

" Set runtime path to include Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"---------------------------------------"
" PLUGINS - keep between vundle#begin/end
"---------------------------------------"

" Let Vundle manage Vundle; required
Plugin 'VundleVim/Vundle.vim'    " V-v-v-vundle
Plugin 'scrooloose/nerdtree'     " Directory structure from vim
Plugin 'chriskempson/base16-vim' " Color schemes 
Plugin 'altercation/vim-colors-solarized'  " Solarized color scheme

"PluginInstall
"PluginUpdate

call vundle#end()

"""""""""""""""""""""""""""""""""
" Activate Powerline status bar "
"""""""""""""""""""""""""""""""""
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

" Set for Powerline-status
set laststatus=2

"--------------"
" VIM SETTINGS "
"--------------"

" This may cause automatic indenting
" If this doesn't format indentions correctly, try the setting 'cindent' and
" 'autoindent'
filetype plugin indent on  " Required for Vundle

" Fix backspace not working unless text is entered right before
set backspace=indent,eol,start

" set tabs to 4 spaces
set ts=4

" Hide buffers instead of closing them when you close the file.
set hidden

" Don't wrap lines
" set nowrap

" Show line numbers by default
set nu

" Highlight matches when searching
set hlsearch

" Show what column the cursor is currently on
set ruler

" Show search matches as you type
" set incsearch

" Set spellcheck on
" Change with `:set spell` or `:set nospell`
"set spell spelllang=en_us

" Set pastetoggle with <F3> key. No smart indenting, just pastes as normal.
set pastetoggle=<F3>

" ignore case when searching (/ or ?)
set ic

" use case-sensitivity when you search w/ upper-case chars
set smartcase

" enter spaces when tab is pressed
set expandtab

" turn on syntax highlighting by default
syntax on

" 256 colors
set t_Co=256

" automatically show matching brackets
set showmatch

" create mapping for quick switch between invisibles and visibles. Enable with `\l`
nmap <leader>l :set list!<CR>

" changes tab and return chars, when visible, to triangle and return symbol, respectively
"set listchars=tab:▸\ ,eol:¬

"---------------"
" COLOR SCHEMES "
"---------------"

" Enable solarized colorscheme
syntax enable

"set background=dark
"set background=light

"colorscheme solarized
"colorscheme base16-3024
"colorscheme base16-brewer
"colorscheme base16-bright
"colorscheme base16-colors
colorscheme base16-default
"colorscheme base16-google " -- Don't like this one. Yellow sucks
"colorscheme base16-harmonic16 " -- Don't like this one either now.
"colorscheme base16-pop "-- too much purple/yellow

"---------"
" ALIASES "
"---------"

" MAPPINGS
:nmap <F2> :NERDTree
