---
- name: Install Alacritty
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure alacritty config dir is present
      ansible.builtin.file:
        path: ~/.config/alacritty
        state: directory
        mode: "0755"
      tags:
        - alacritty

    - name: Install Alacritty config file
      ansible.builtin.copy:
        src: roles/development/files/alacritty.toml
        dest: ~/.config/alacritty/alacritty.toml
        mode: "0644"
      tags:
        - alacritty
