---
- name: Install (neo)vim
  hosts: localhost
  connection: local
  vars:
    nvim_version: v0.9.5
  tasks:
    - name: Install vim
      ansible.builtin.package:
        name:
          - vim
        state: latest
      become: true

    # TODO: install Node/npm for lazyvim
    # $ curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh
    # $ sudo -E bash nodesource_setup.sh
    # $ sudo apt-get install -y nodejs

    # TODO: Install/update rust
    # TODO: Install rust-analyzer (see https://rust-analyzer.github.io/manual.html#rust-analyzer-language-server-binary)
    # or maybe $ rustup component add rust-analyzer
    # TODO: install rust src ($ rustup component add rust-src)

    # TODO: Only download if not present in ~/bin
    - name: Download neovim
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/nvim.appimage
        dest: /tmp/nvim-{{ nvim_version }}.appimage
        checksum: sha256:0c82e5702af7a11fbb916a11b4a82e98928abf8266c74b2030ea740340437bf9
        mode: "0755"
      tags:
        - vim

    - name: Move nvim appimage to ~/bin
      ansible.builtin.copy:
        src: /tmp/nvim-{{ nvim_version }}.appimage
        dest: ~/bin/nvim-{{ nvim_version }}.appimage
        mode: "0755"
      tags:
        - vim

    - name: Create nvim symlink in ~/bin
      ansible.builtin.file:
        src: ~/bin/nvim-{{ nvim_version }}.appimage
        dest: ~/bin/nvim
        state: link
        force: true
      tags:
        - vim

    - name: Clean up downloaded file
      ansible.builtin.file:
        path: /tmp/nvim-{{ nvim_version }}.appimage
        state: absent

    - name: Ensure neovim config directory structure exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - ~/.config/nvim/lua/plugins
        - ~/.config/nvim/lua/config
      tags:
        - vim

    - name: Copy neovim config file into place
      ansible.builtin.copy:
        src: files/init.lua
        dest: ~/.config/nvim/init.lua
        mode: "0644"
      tags:
        - vim

    # TODO: Install lazyvim config files into place
    - name: Copy lazyvim config files into place
      ansible.builtin.copy:
        src: files/nvim_lua/
        dest: ~/.config/nvim/lua/
      tags:
        - vim
